In [1]:
import torch
import numpy as np
import time

In [13]:
d = 3000
a = np.random.rand(d, d)
b = np.random.rand(d, d)
start = time.time()
c = np.matmul(a, b)
end = time.time()
print("Numpy time: ", end - start)

gpu = torch.device("mps")
a = torch.rand(d, d, device=gpu)
b = torch.rand(d, d, device=gpu)
start = time.time()
c = torch.matmul(a, b)
end = time.time()
print("Pytorch time: ", end - start)


Numpy time:  0.4936249256134033
Pytorch time:  0.0011589527130126953


In [17]:
# Let's construct a 5x3 matrix, uninitialized:
x = torch.Tensor(5, 3)
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [33]:
# Construct a randomly initialized matrix:
x = torch.rand(5, 3)
print(x)

tensor([[0.9453, 0.9257, 0.5468],
        [0.1820, 0.5939, 0.5335],
        [0.4598, 0.6279, 0.6268],
        [0.6108, 0.5825, 0.0353],
        [0.4305, 0.3577, 0.4126]])


In [31]:
# Get its size:
print(x.size())
print(x.shape)

torch.Size([5, 3])
torch.Size([5, 3])


In [38]:
print(x[:, 1])

tensor([0.9257, 0.5939, 0.6279, 0.5825, 0.3577])


In [39]:
# Let's sum two tensors
y = torch.rand(5, 3)
print(x + y)

tensor([[1.8981, 1.7695, 0.8515],
        [0.5923, 0.6486, 1.4083],
        [1.2633, 1.4692, 0.7060],
        [1.4272, 1.2935, 0.5364],
        [0.8537, 1.1916, 1.1097]])


In [43]:
# Numpy bridge
# Converting a Torch Tensor to a NumPy array and vice versa is a breeze.
# The Torch Tensor and NumPy array will share their underlying memory locations,
# and changing one will change the other.

# Converting a Torch Tensor to a NumPy Array
a = torch.ones(5)
print(a)

b = a.numpy()
print(b)


tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]


In [44]:
# See how the numpy array changed in value.
a.add_(2)
print(a)
print(b)


tensor([3., 3., 3., 3., 3.])
[3. 3. 3. 3. 3.]


In [45]:
a = np.ones((5,))
b = torch.from_numpy(a)

np.multiply(a, 2, out=a)
print(a)
print(b)


[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
